baseURL = 'https://ro.speace.de/p/'
languageCode = 'ru'
title = 'Официальный сайт организации «Депутаты Мирной России»'
theme = 'ananke'

[params]
  custom_css = ["custom.css"]
  telegram = "https://t.me/mir_dep"
  feedback_bot = "https://t.me/mundep_feedback_bot"
